name: actions-k3s
description: Start k3s cluster and run kubectl commands
inputs:
  version:  
    description: Version of k3s
    required: true
  arguments:
    description: Arguments for k3s
    required: false
  ports:
    description: Comma delimited list of host_port:container_port values (example "80:80,8080:8080")
    required: false
outputs:
  kubeconfig:
    description: Kubeconfig location
branding:
  icon: box
  color: green
runs:
  using: node16
  main: dist/index.js
