name: k3s Testing
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./
        with:
          version: 'latest'
      - run: |
          kubectl get nodes