name: k3s Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./
        with:
          version: 'latest'
  #    - uses: replicatedhq/actions-k3s@${{github.ref_name}}
  #      id: k3s
  #      with:
  #        version: 'latest'
      - run: |
          kubectl get nodes