name: k3s Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: ./action.yml
#      id: k3s
#      with:
#        version: 'latest'
    - uses: replicatedhq/actions-k3s@${{github.ref_name}}
      id: k3s
      with:
        version: 'latest'
    - run: |
        kubectl get nodes